name: Validate Workflows

on:
  pull_request:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  push:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
