name: CI
on:
  push:
  pull_request:

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pandas openpyxl python-docx reportlab markdownlint-cli
      - name: Markdown lint
        run: |
          npx --yes markdownlint-cli "**/*.md" || true
      - name: PDF smoke test (no-op if CSV missing)
        run: |
          test -f generate_batch_pdf.py || exit 0
          python generate_batch_pdf.py --batch 03 --repo . --index 99_Master_Index.csv || true
