name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pytest
      - name: Run tests
        run: python -m pytest -q

  md-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Markdown Lint
        run: |
          # Use our config & ignore files from repo root
          markdownlint-cli2 "**/*.md" \
            --config .markdownlint.json \
            --ignore-path .markdownlintignore
