name: Markdown Lint
on:
  pull_request:
    paths:
      - "**/*.md"
  push:
    paths:
      - "**/*.md"
jobs:
  md-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Install markdownlint-cli2
        run: npm -g i markdownlint-cli2
      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md"
