name: Draft Release on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # required for creating releases

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        id: notes
        uses: release-drafter/release-drafter@v6
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            See CHANGELOG.md for details. If missing, auto notes below:

            ${{ steps.notes.outputs.body }}

          # Adjust these paths to wherever you output the PDF
          files: |
            MasterFile_Batch_03.pdf
            02_Batches/Batch_03/MasterFile_Batch_03.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
